name: 'Junit Report to Annotations'
description: 'Create an annotation of the test run summaryand also list first n failed tests as seporate annotations'
inputs:
  value:
    description: 'input string to apply regex to'
    required: true
  regex:
    description: 'regex to apply'
    required: true
  replacement:
    description: 'replacement string'
    default: "$1"
    required: true
outputs:
  value:
    description: 'regex replaced property'
runs:
  using: 'node12'
  main: 'index.js'
